name: Docs build

on:
  pull_request:
    types: [opened, closed, synchronize]
  push:
  workflow_dispatch:

jobs:
  Build:
    uses: hyperspy/.github/.github/workflows/doc.yml@main
    with:
      pip_extra_doc: 'all,doc'
      install_package_ubuntu: graphviz optipng
      check_links: true
      doctest: false
      SPHINXOPTS: '--jobs 4' # use parallel build to speed up builds
      ORGANISATION: 'pyxem'
      CACHE_GALLERY_EXAMPLES: './doc/examples' # cache sphinx-gallery examples for faster builds
      CACHE_POOCH: 'pyxem' # cache pooch downloads for pyxem data

  Redirect-stable:
    # build a redirect index.html to the stable version on tag builds
    if: github.ref_type == 'tag' 
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Build index redirect
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          mkdir -p redirect
          cat <<EOF > redirect/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=${VERSION}/">
              <script>window.location.href='${VERSION}/';</script>
            </head>
            <body>
              <p>Redirecting to the <a href="${VERSION}/">documentation (stable)</a>...</p>
            </body>
          </html>
          EOF
      - uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          path: redirect
          name: redirect

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Write deploy info to file
        run: |
          mkdir -p deploy_info
          cat <<EOF > deploy_info/info.json
          {
            "workflow_run_id": "${{ github.run_id }}",
            "pr_number": "${{ github.event.pull_request.number || '' }}",
            "ref_type": "${{ github.ref_type }}",
            "ref_name": "${{ github.ref_name }}",
            "pull_request_action": "${{ github.event.action || '' }}"
          }
          EOF

      - name: Upload deploy info artifact # For the follow up deploy job
        uses: actions/upload-artifact@v4
        with:
          name: deploy-info
          path: deploy_info/info.json