name: Docs deploy

on:
  workflow_run:
    workflows: ["Docs build"]
    types: [completed]

env:
  html_folder: ./doc/_build/html
  artifact_name: doc_html

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Download deploy info artifact
        uses: actions/download-artifact@v5
        with:
          name: deploy-info
          path: deploy_info
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse deploy info
        id: info
        run: |
          echo "Parsing deploy_info/info.json:"
          cat deploy_info/info.json
          echo "workflow_run_id=$(jq -r '.workflow_run_id' deploy_info/info.json)" >> $GITHUB_OUTPUT
          echo "ref_type=$(jq -r '.ref_type' deploy_info/info.json)" >> $GITHUB_OUTPUT
          echo "ref_name=$(jq -r '.ref_name' deploy_info/info.json)" >> $GITHUB_OUTPUT
          echo "pr_number=$(jq -r '.pr_number' deploy_info/info.json)" >> $GITHUB_OUTPUT
          echo "pull_request_action=$(jq -r '.pull_request_action' deploy_info/info.json)" >> $GITHUB_OUTPUT

      - name: Download built docs
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.html_folder }}
          run-id: ${{ steps.info.outputs.workflow_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print doc files
        run: ls -l ${{ env.html_folder }}

      - name: Deploy dev docs
        if: ${{ steps.info.outputs.ref_name == 'main' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.html_folder }}
          destination_dir: dev

      - name: Deploy PR preview
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action != 'closed' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          personal_token: ${{ secrets.PREVIEW_DEPLOY_KEY }}
          publish_dir:  ${{ env.html_folder }}
          destination_dir: pr-preview/${{ steps.info.outputs.pr_number }}
          external_repository: CSSFrancis/pyxem-docs-staging

      - name: Get timestamp (UTC)
        if: ${{ steps.info.outputs.pr_number != '' }}
        id: timestamp
        run: |
          echo "utc=$(date -u '+%Y-%m-%d %H:%M UTC')" >> "$GITHUB_OUTPUT"

      - name: Post preview link as sticky PR comment
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action != 'closed' }}
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        with:
          number: ${{ steps.info.outputs.pr_number }}
          header: pr-preview
          message: |
            **PR Preview**
            :---:
            :rocket: View PR Preview at https://cssfrancis.github.io/pyxem-docs-staging/pr-preview/pr-${{ steps.info.outputs.pr_number }}.
            If you see a 404 error, please wait a few seconds for the deployment to complete and refresh the page.
            ${{ steps.timestamp.outputs.utc }}

      - name: Create empty deploy folder
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action == 'closed' }}
        run: mkdir -p empty

      - name: Remove PR preview
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action == 'closed' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          personal_token: ${{ secrets.PREVIEW_DEPLOY_KEY }}
          publish_dir: ./empty
          destination_dir: pr-preview/${{ steps.info.outputs.pr_number }}
          external_repository: CSSFrancis/pyxem-docs-staging

      - name: Update sticky PR comment
        if: ${{ steps.info.outputs.pr_number != '' && steps.info.outputs.pull_request_action == 'closed' }}
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405
        with:
          number: ${{ steps.info.outputs.pr_number }}
          header: pr-preview
          message: |
            **PR Preview**
            :---:
            Preview removed because the pull request was closed.
            ${{ steps.timestamp.outputs.utc }}

      - name: Deploy versioned docs
        if: ${{ steps.info.outputs.ref_type == 'tag' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.html_folder }}
          destination_dir: ${{ steps.info.outputs.ref_name }}

      - name: Download redirect files
        if: ${{ steps.info.outputs.ref_type == 'tag' }}
        uses: actions/download-artifact@v5
        with:
          name: redirect
          path: redirect
          run-id: ${{ steps.info.outputs.workflow_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy redirect to versioned docs
        if: ${{ steps.info.outputs.ref_type == 'tag' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: redirect
          destination_dir: .
          keep_files: true

